### PR TITLE
F/dinamic ip

### PR DESCRIPTION
**Pull request by JonatanSCS**
* Solve `unique key` warning from `ip.reduce`code from IPCard component
* Update `material-ui`dependencies
* Solve variant warning from `material-ui`
* Set dinamically your current IP and use it to get your location data
* Get your browser data in display it

### CODE REVIEW

**Comment by JonatanSCS** [comment]
Is really necessary use that server?
Or you asking for remove it?

**Comment by rakhi2104** [comment]
If we already have an API to get the Location, why write again ?

**Comment by JonatanSCS** [comment]
Because is useless for localhost, if someone try tu use the app locally it doesn't works.

Or Im not seeing anything?
Hows the app supposed to be if you are using it  on localhost?

**Comment by JonatanSCS** [comment]
That's ok, but doesn't answer my question `How's the app supposed to be if you are using it on localhost?` 

Showing a localhost error or hardcoding `8.8.8.8` IP?

**Comment by Dgiulian** [comment]
I've created a PR that moves the query to the IPAPI to the server, so this eliminates the need to make the request from the browser.

**Comment by JonatanSCS** [comment]
@Dgiulian Perfect, im check your PR and its great.
Im gonna close this PR and send a PR with little changes

**Pull request closed without merging**
